### PR TITLE
Updating helm charts

### PR DESCRIPTION
**Pull request by denismakogon**
- Do not deploy Fn UI until it would become working again
 - Fn is in distributed mode: 1 API, 1 LB, 3 nodes.
 - every invoke and trigger paths are annotated with DNS names in values.yaml.

 Notes:
 - a number of exposed ports remain the same ( 1 for Flow UI, 2 for API and LB)
 - updating Fn version
 - pinning Flow version

### CODE REVIEW

**Comment by carimura** [comment]
fine for now but we've got to fix the UI ASAP.

**Comment by carimura** [comment]
Also why the Flow port change? Worked before as a Cluster IP?

**Comment by denismakogon** [comment]
Flow port didn’t changed. It works now on port 80 since it’s a port mapping, so, the flow works through port forwarding from public 80 to 8081.

**Comment by carimura** [comment]
sorry meant servicetype change. Why the change now?

**Comment by denismakogon** [comment]
Because with ClusterIP does not guarantee a public IP reachable from outside.

**Comment by carimura** [comment]
does Flow need to be reachable from outside if used from Fn funcs?

**Comment by denismakogon** [comment]
So, tend to agree, exposing flow service is not necessary, but lots of things need to be changed like:
 - fnlb (fnproject/lb) is outdated
 - advanced deployment model for Fn is necessary (based on FN_NODE_TYPE).

What's done so far:
 - lb gone
 - Fn is a single container for now, will evolve into distributed Fn
 - chart value tweaks like Fn container port, etc.

**Comment by devcamcar** [comment]
I'm still seeing issues deploying the gofn example.  The deployment itself works fine:

    $ fn list app
    NAME	ID
    goapp	01CVXMRS431BT044R0A0000001

But I am unable to invoke the function:

    $ fn list app
    NAME	ID
    goapp	01CVXMRS431BT044R0A0000001
    ubuntu@bastion:~$ fn --verbose invoke goapp gofn
    Error:

    Fn: Error calling function: status 404

    See 'fn <command> --help' for more information. Client version: 0.5.29

Strangely, I don't see anything in the API, LB or runner logs during these attempts.  I also get 404s when invoking manually:

    $ curl -H "Content-Type: application/json" http://129.146.92.219:80/t/goapp/gofn-trigger
    {"message":"Path not found: /t/goapp/gofn-trigger"}

**Comment by denismakogon** [comment]
Because in hybrid mode you need to call functions through LB, but not
through API node. Only “full” node can do all: API queries and execute
function. In this deployment model you don’t have “full” node (this is what
`fn start` gives you), only api, lb, and pure runners.

**Comment by devcamcar** [comment]
Also can you help me understand what the invoke url here means?  It is returning the fn-api k8s service IP when I expected to see the fn-lb k8s service IP based on your above description:

    $ fn inspect function goapp gofn
    {
    	"annotations": {
    		"fnproject.io/fn/invokeEndpoint": "http://129.146.155.239:80/invoke/01CVZHYYEY1BT024R0A0000002"
    	},
    	"app_id": "01CVZHYYEQ1BT024R0A0000001",
    	"created_at": "2018-11-10T19:35:44.862Z",
    	"id": "01CVZHYYEY1BT024R0A0000002",
    	"idle_timeout": 30,
    	"image": "devcamcar/gofn:0.0.19",
    	"memory": 128,
    	"name": "gofn",
    	"timeout": 30,
    	"updated_at": "2018-11-10T19:35:44.862Z"
    }

**Comment by devcamcar** [comment]
@denismakogon Intuitively it feels like all the CLI requests should hit fn-api.  Perhaps fn-api should pass `invoke` and related commands to fn-lb?  Would make it more clear that fn-lb is really fn-runner-lb?

**Comment by denismakogon** [comment]
@devcamcar I figured out how to make it work. Unfortunately, our docs are slightly outdated, so, you'd still be capable to call a function with `fn invoke` without specifying runner LB host. Every API node needs `FN_PUBLIC_LB_URL` (`http://my.lb.address:port`) to be set, this env var points to a runner LB service. For every function API node will annotate it with LB address, it means that `fn invoke` will work out of the box.
I'll post a new version soon, but having some infra problems, will test it later.

**Comment by denismakogon** [comment]
Finally, it works. The only thing that is left undone - doc.

**Comment by denismakogon** [comment]
would you mind to provide an output of:
```
fn inspect fn goapp gofn
```

and provide `kube get svc | grep <your-release-name>` ?

**Comment by devcamcar** [comment]
fn inspect output:

    $ fn inspect fn goapp gofn
    {
    	"annotations": {
    		"fnproject.io/fn/invokeEndpoint": "http://lb.fnservice.io:90/invoke/01CWQ0WMBP1BT02580A0000002"
    	},
    	"app_id": "01CWQ0KE5R1BT02580A0000001",
    	"created_at": "2018-11-19T22:19:09.558Z",
    	"id": "01CWQ0WMBP1BT02580A0000002",
    	"idle_timeout": 30,
    	"image": "devcamcar/gofn:0.0.21",
    	"memory": 128,
    	"name": "gofn",
    	"timeout": 30,
    	"updated_at": "2018-11-19T22:19:09.558Z"
    }

    $ kubectl get svc | grep fn-release
    fn-release-fn          LoadBalancer   10.96.110.65    129.146.149.62    80:31060/TCP,90:30717/TCP             1h
    fn-release-fn-flow     ClusterIP      10.96.178.215   <none>            80/TCP                                1h
    fn-release-fn-runner   ClusterIP      10.96.220.97    <none>            9191/TCP                              1h
    fn-release-fn-ui       LoadBalancer   10.96.63.199    129.146.211.167   3000:30058/TCP                        1h
    fn-release-mysql       ClusterIP      10.96.90.238    <none>            3306/TCP                              1h
    fn-release-redis       ClusterIP      10.96.144.153   <none>            6379/TCP                              1h

**Comment by denismakogon** [comment]
I see. Here's the thing, I guess you didn't notice (in NOTES.txt) that you need to set your own public DNS names. `lb.fnservice.io` is not yours, so, you have to point modify your values.yml to make it work for you, see `lb_dns_name` and `api_dns_name`

**Comment by devcamcar** [comment]
Yes, I missed that, sorry :)

Got it - I'll make that change and try again.

**Comment by devcamcar** [comment]
Okay - I've updated DNS names as instructed and now everything works great.

**Comment by denismakogon** [comment]
@devcamcar stay tuned, i'll add ingress support soon, so, number of LoadBalancers will be reduced in favour of a single ingress controller.

**Comment by carimura** [comment]
+1

**Pull request merged**
